"use client"

import { useState } from "react"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs"
import { Badge } from "@/components/ui/badge"
import { Presentation, RefreshCw, Download, Users, TrendingUp, Target, DollarSign } from "lucide-react"

interface PitchDeckData {
  problem: string
  solution: string
  market: string
  businessModel: string
  traction: string
  competition: string
  team: string
  financials: string
  ask: string
}

export function PitchDeck() {
  const [startupIdea, setStartupIdea] = useState("")
  const [targetMarket, setTargetMarket] = useState("")
  const [isGenerating, setIsGenerating] = useState(false)
  const [hasDeck, setHasDeck] = useState(false)

  const [deck, setDeck] = useState<PitchDeckData>({
    problem: "",
    solution: "",
    market: "",
    businessModel: "",
    traction: "",
    competition: "",
    team: "",
    financials: "",
    ask: ""
  })

  const generateDeck = async () => {
    if (!startupIdea || !targetMarket) {
      alert("Please enter both startup idea and target market");
      return;
    }

    setIsGenerating(true)
    setHasDeck(false)

    try {
      const API_URL = "http://127.0.0.1:8000"
      const response = await fetch(`${API_URL}/pitch-deck`, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          startup_idea: startupIdea,
          target_market: targetMarket,
        }),
      });

      if (!response.ok) {
        throw new Error("Failed to generate pitch deck");
      }

      const data = await response.json();
      
      if (data.deck) {
        setDeck(data.deck);
        setHasDeck(true);
      } else {
        throw new Error("Invalid response format");
      }
      
    } catch (error) {
      console.error("Error generating deck:", error);
      alert("Failed to generate pitch deck. Please try again.");
    } finally {
      setIsGenerating(false);
    }
  };

  const exportPitchDeck = async () => {
    try {
      setIsGenerating(true);
      
      const deckContent = `
PITCH DECK - ${startupIdea}

PROBLEM:
${deck.problem}

SOLUTION:
${deck.solution}

MARKET OPPORTUNITY:
${deck.market}

BUSINESS MODEL:
${deck.businessModel}

TRACTION:
${deck.traction}

COMPETITION:
${deck.competition}

TEAM:
${deck.team}

FINANCIALS:
${deck.financials}

FUNDING ASK:
${deck.ask}

Generated by AI Co-Founder on ${new Date().toLocaleDateString()}
      `;
      
      const blob = new Blob([deckContent], { type: "text/plain" });
      const url = window.URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = `pitch_deck_${new Date().getTime()}.txt`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      window.URL.revokeObjectURL(url);
      
    } catch (error) {
      console.error("Error exporting deck:", error);
      alert("Failed to export pitch deck");
    } finally {
      setIsGenerating(false);
    }
  };

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-3xl font-bold mb-2">Pitch Deck Generator</h1>
        <p className="text-muted-foreground">
          Generate an investor-ready pitch deck for your startup.
        </p>
      </div>

      {/* Input Section */}
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <Presentation className="w-5 h-5 text-primary" />
            Startup Information
          </CardTitle>
          <CardDescription>
            Enter details about your startup to generate a pitch deck.
          </CardDescription>
        </CardHeader>

        <CardContent className="space-y-4">
          <div className="grid md:grid-cols-2 gap-4">
            <div className="space-y-2">
              <Label>Startup Idea</Label>
              <Input
                placeholder="AI startup for healthcare..."
                value={startupIdea}
                onChange={(e) => setStartupIdea(e.target.value)}
              />
            </div>

            <div className="space-y-2">
              <Label>Target Market</Label>
              <Input
                placeholder="Hospitals, Developers, SMBs..."
                value={targetMarket}
                onChange={(e) => setTargetMarket(e.target.value)}
              />
            </div>
          </div>

          <Button onClick={generateDeck} disabled={isGenerating} className="w-full md:w-auto">
            {isGenerating ? (
              <>
                <RefreshCw className="w-4 h-4 mr-2 animate-spin" />
                Generating Deck...
              </>
            ) : (
              <>
                <Presentation className="w-4 h-4 mr-2" />
                Generate Pitch Deck
              </>
            )}
          </Button>
        </CardContent>
      </Card>

      {/* Results */}
      {hasDeck && (
        <Tabs defaultValue="problem" className="space-y-4">
          <TabsList className="grid grid-cols-2 md:grid-cols-5 w-full">
            <TabsTrigger value="problem">Problem</TabsTrigger>
            <TabsTrigger value="solution">Solution</TabsTrigger>
            <TabsTrigger value="market">Market</TabsTrigger>
            <TabsTrigger value="business">Business</TabsTrigger>
            <TabsTrigger value="financials">Financials</TabsTrigger>
          </TabsList>

          <TabsContent value="problem">
            <Card>
              <CardHeader>
                <CardTitle className="flex items-center gap-2">
                  <Target className="w-5 h-5 text-primary" />
                  Problem
                </CardTitle>
              </CardHeader>
              <CardContent>{deck.problem}</CardContent>
            </Card>
          </TabsContent>

          <TabsContent value="solution">
            <Card>
              <CardHeader>
                <CardTitle>Solution</CardTitle>
              </CardHeader>
              <CardContent>{deck.solution}</CardContent>
            </Card>
          </TabsContent>

          <TabsContent value="market">
            <Card>
              <CardHeader>
                <CardTitle className="flex items-center gap-2">
                  <Users className="w-5 h-5 text-primary" />
                  Market Opportunity
                </CardTitle>
              </CardHeader>
              <CardContent>{deck.market}</CardContent>
            </Card>
          </TabsContent>

          <TabsContent value="business">
            <Card>
              <CardHeader>
                <CardTitle>Business Model</CardTitle>
              </CardHeader>
              <CardContent>
                <p className="mb-4">{deck.businessModel}</p>
                <div className="mt-2">
                  <h4 className="font-semibold mb-2">Competition:</h4>
                  <p className="text-muted-foreground">{deck.competition}</p>
                </div>
              </CardContent>
            </Card>
          </TabsContent>

          <TabsContent value="financials">
            <Card>
              <CardHeader>
                <CardTitle className="flex items-center gap-2">
                  <DollarSign className="w-5 h-5 text-primary" />
                  Financials & Funding Ask
                </CardTitle>
              </CardHeader>

              <CardContent className="space-y-4">
                <div>
                  <h4 className="font-semibold mb-2">Financial Projections:</h4>
                  <p>{deck.financials}</p>
                </div>
                
                <div>
                  <h4 className="font-semibold mb-2">Funding Ask:</h4>
                  <Badge variant="secondary" className="text-sm">
                    {deck.ask}
                  </Badge>
                </div>

                <div>
                  <h4 className="font-semibold mb-2">Traction:</h4>
                  <p className="text-muted-foreground">{deck.traction}</p>
                </div>

                <div>
                  <h4 className="font-semibold mb-2">Team:</h4>
                  <p className="text-muted-foreground">{deck.team}</p>
                </div>

                <Button 
                  className="w-full" 
                  onClick={exportPitchDeck}
                  disabled={isGenerating}
                >
                  {isGenerating ? (
                    <>
                      <RefreshCw className="w-4 h-4 mr-2 animate-spin" />
                      Exporting...
                    </>
                  ) : (
                    <>
                      <Download className="w-4 h-4 mr-2" />
                      Export Pitch Deck
                    </>
                  )}
                </Button>
              </CardContent>
            </Card>
          </TabsContent>
        </Tabs>
      )}
    </div>
  )
}